name: Set up Rust and associated tools

inputs:
  package:
    description: Package to run. Can use wildcards.
    type: string
    required: false
    default: "*"
  extra_args:
    description: Additional args
    type: string
    required: false
    default:

runs:
  using: composite
  steps:
    - name: Install cargo nextest
      uses: taiki-e/install-action@nextest
    - name: Run MC tests
      shell: bash
      env:
      run: |
        # tell the operating system to remove the file size limit on core dump files
        ulimit -c unlimited

        # Run tests, with JUnit XML output configured via .config/nextest.toml
        cargo nextest run --workspace --tests -p "${{ inputs.package }}" -j 4 \
          --profile ci ${{ inputs.extra_args }}
    - name: Collect core dumps
      uses: actions/upload-artifact@v3
      with:
        name: core_dumps
        path: core.*
        if-no-files-found: ignore
    - name: Check dirty git
      uses: ./.github/actions/check-dirty-git
