name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - develop
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  run-mc-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup-rust
      - name: Run tests
        uses: ./.github/actions/run-mc-tests
        with:
          test_command: cargo test --workspace --exclude "mc-fog-*" --exclude "mc-consensus-*" --target "$HOST_TARGET_TRIPLE" --no-fail-fast --tests -j 4

  run-consensus-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup-rust
      - name: Run tests
        uses: ./.github/actions/run-mc-tests
        with:
          test_command: cargo test --workspace --package "mc-consensus-*" -j 4 --no-fail-fast

  run-fog-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup-rust
      - name: Run tests
        uses: ./.github/actions/run-mc-tests
        with:
          test_command: cargo test --workspace --package "mc-fog-*" --exclude "mc-fog-ingest-*" -j 4 --no-fail-fast

  run-fog-ingest-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup-rust
      - name: Run tests
        uses: ./.github/actions/run-mc-tests
        with:
          test_command: cargo test --workspace --package "mc-fog-ingest-*" -j 4 --no-fail-fast


# via https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
